# Generated by Django 5.1.6 on 2025-04-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0004_alter_student_program_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentorg.program'),
        ),
    ]
